# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Dakota Reed
tagline:          'My bkig'
description:      'My blog'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Dakota Reed'
  url:            https://twitter.com/dakotalreed

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dackq

disqus: blog-dakotalreed.com
